# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:13:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ResultFormat(Enum):
    json = 'json'
    xml = 'xml'
    kml = 'kml'
    kmz = 'kmz'
    shp = 'shp'
    shpz = 'shpz'
    geojson = 'geojson'
    gml = 'gml'
    gpkg = 'gpkg'
    wkt = 'wkt'


class AllowOverlap(Enum):
    boolean_False = False
    boolean_True = True


class BufferJoin(Enum):
    ROUND = 'ROUND'
    MITRE = 'MITRE'
    BEVEL = 'BEVEL'


class BufferCap(Enum):
    ROUND = 'ROUND'
    SQUARE = 'SQUARE'
    FLAT = 'FLAT'


class Format(Enum):
    json = 'json'
    xml = 'xml'
    kml = 'kml'
    kmz = 'kmz'
    shp = 'shp'
    shpz = 'shpz'
    geojson = 'geojson'
    gml = 'gml'
    gpkg = 'gpkg'
    wkt = 'wkt'


class Multiple(Enum):
    boolean_False = False
    boolean_True = True


class Srid(Enum):
    integer_4326 = 4326
    integer_3005 = 3005
    integer_3857 = 3857
    integer_26907 = 26907
    integer_26908 = 26908
    integer_26909 = 26909
    integer_26910 = 26910
    integer_26911 = 26911


class GeomarksNewPostRequest(BaseModel):
    allowOverlap: Optional[AllowOverlap] = Field(
        False,
        description='When multiple=true select this option to allow overlapping geometries',
    )
    body: Optional[str] = Field(
        None,
        description='The binary or character content representing the geometry or geometries',
    )
    bufferCap: Optional[BufferCap] = Field(
        'ROUND',
        description='If bufferMetres is specified, The style of buffer to use at the ends of a buffered line.',
    )
    bufferJoin: Optional[BufferJoin] = Field(
        'ROUND',
        description='If bufferMetres is specified, The style of buffer to use for joins between the line segments for lines and polygons.',
    )
    bufferMetres: Optional[int] = Field(
        None,
        description='The amount to buffer the geometry in metres, must only contain numerical digits (e.g 10). Leave blank and no buffer will be added to input geometries. If blank then any Point, LineString, MultiPoint and MultiLineString geometries will be ignored.',
    )
    bufferMitreLimit: Optional[int] = Field(
        5,
        description='If bufferMetres is specified, the maximum ratio of distance from the original geometry to a mitre buffer point and the buffer amount. If the ratio is greater than this a bevel will be used instead. This prevents infinite distances when the angle between the two lines at a join is small. Must be > 0.',
    )
    bufferSegments: Optional[int] = Field(
        8,
        description='If bufferMetres is specified, the number of line segments used in each quadrant to approximate the curve for round end-cap and join styles. Must be > 0.',
    )
    callback: Optional[str] = Field(
        None,
        description='The callback function a JSON result format would be wrapped in to support Ajax requests.',
    )
    failureRedirectUrl: Optional[str] = Field(
        None,
        description='The url to redirect if the geomark could not be created. The URL will include a <fieldName>_Error parameter with the error message for the field that caused the error.',
    )
    format: Optional[Format] = Field(
        None, description='The file format name extension of the input geometry.'
    )
    multiple: Optional[Multiple] = Field(
        False,
        description='Boolean flag indicating if multiple geometries are to be used for the geomark (true) or only a single geometry from the first geometry (false).',
    )
    redirectUrl: Optional[str] = Field(
        None,
        description='The optional external URL to redirect the user to when the geomark is created rather than showing the geomark info page. The geomarkId and geomarkUrl query string parameters will be added to the redirectUrl so that the target application gets a reference to the geomark.',
    )
    resultFormat: Optional[ResultFormat] = Field(
        None,
        description='The file format the geomark info resource should be returned using.',
    )
    srid: Optional[Srid] = Field(
        4326,
        description='The srid of the coordinate system the input geometries are in. If the file includes a coordinate system definition that will be used.',
    )


class FileFormatExtension(Enum):
    json = 'json'
    xml = 'xml'
    kml = 'kml'
    kmz = 'kmz'
    shp = 'shp'
    shpz = 'shpz'
    geojson = 'geojson'
    gml = 'gml'
    gpkg = 'gpkg'
    wkt = 'wkt'
